dataset:
  data_folder: 'caption data'
  data_name: 'coco_5_cap_per_img_5_min_word_freq' 
model:
optimizer:
  lr: 1e-1
  weight_decay: 0
train:
  hidden_size: 400
  hidden_layer_num: 2
  hidden_dropout_prob: 0.5
  input_dropout_prob: 0.2
  task_number: 3
  epochs_per_task: 3
  lamda: 40
  batch_size: 128
  test_size: 1024
  fisher_estimation_sample_size: 1024
  
evaluate:
  batch_size: 1000
  augmentation_factor: 32
